# Generated by Django 5.2.16 on 2026-07-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('denunciante', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('progreso', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_tiempo', 'En tiempo'), ('atrasada', 'Atrasada'), ('en_riesgo', 'En riesgo'), ('completada', 'Completada')], max_length=50)),
                ('criticidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('atrasado', 'Atrasado'), ('por_hacer', 'Por hacer')], max_length=50)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('impacto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('probabilidad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('mitigado', 'Mitigado'), ('en_curso', 'En curso')], max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('fecha_identificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('revisando', 'Revisando'), ('resolviendo', 'Resolviendo'), ('resuelta', 'Resuelta')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('sla', models.CharField(choices=[('en_tiempo', 'En tiempo'), ('en_riesgo', 'En riesgo'), ('atrasada', 'Atrasada')], max_length=50)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('urgente', 'Urgente'), ('media', 'Media')], max_length=50)),
                ('solicitante', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TareaPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('vencido', 'Vencido'), ('al_dia', 'Al día'), ('en_progreso', 'En progreso')], max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('tarea', models.CharField(max_length=255)),
                ('asociada_a', models.CharField(max_length=100)),
                ('responsable_asignado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoRAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=255)),
                ('finalidad', models.TextField()),
                ('categoria_dp', models.CharField(max_length=100)),
                ('base_licitud', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('borrador', 'Borrador')], max_length=50)),
            ],
        ),
    ]
