# Generated by Django 5.2.16 on 2026-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empresa_incidente_empresa_normativa_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareapendiente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], max_length=50),
        ),
    ]
