# Generated by Django 6.1 on 2026-08-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_control_area_auditoria_eventocompliance_evidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='setup_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamano',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
