# Generated by Django 6.1 on 2026-08-10 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_empresa_rubro_empresa_setup_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='es_b2c_ecommerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='genera_residuos_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='maneja_datos_personales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='procesa_pagos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rango_empleados',
            field=models.CharField(choices=[('MICRO', 'Micro (1-9 colaboradores)'), ('PEQUENA', 'Pequeña (10-49 colaboradores)'), ('MEDIANA', 'Mediana (50-199 colaboradores)'), ('GRANDE', 'Grande (200+ colaboradores)')], default='PEQUENA', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tiene_trabajadores',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_sociedad',
            field=models.CharField(choices=[('SPA', 'Sociedad por Acciones (SpA)'), ('SA', 'Sociedad Anónima (S.A.)'), ('LTDA', 'Sociedad de Responsabilidad Limitada (Ltda.)'), ('EIRL', 'Empresa Individual de Resp. Ltda. (EIRL)'), ('PERSONA_NATURAL', 'Persona Natural con Giro')], default='SPA', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='normativa',
            name='codigo_bcn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normativa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normativa',
            name='es_transversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normativa',
            name='min_empleados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='normativa',
            name='requiere_b2c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normativa',
            name='requiere_datos_personales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normativa',
            name='requiere_procesa_pagos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normativa',
            name='requiere_residuos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normativa',
            name='requiere_trabajadores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normativa',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normativa',
            name='rubro_aplicable',
            field=models.CharField(blank=True, choices=[('TECNOLOGIA', 'Tecnología y Software'), ('SALUD', 'Salud y Clínicas'), ('MINERIA', 'Minería y Energía'), ('RETAIL', 'Retail y Comercio'), ('ALIMENTOS', 'Alimentos y Bebidas'), ('FINANCIERO', 'Servicios Financieros (Fintech)'), ('CONSTRUCCION', 'Construcción e Inmobiliaria'), ('EDUCACION', 'Educación'), ('SERVICIOS', 'Servicios Profesionales')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='normativa',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(choices=[('TECNOLOGIA', 'Tecnología y Software'), ('SALUD', 'Salud y Clínicas'), ('MINERIA', 'Minería y Energía'), ('RETAIL', 'Retail y Comercio'), ('ALIMENTOS', 'Alimentos y Bebidas'), ('FINANCIERO', 'Servicios Financieros (Fintech)'), ('CONSTRUCCION', 'Construcción e Inmobiliaria'), ('EDUCACION', 'Educación'), ('SERVICIOS', 'Servicios Profesionales')], default='TECNOLOGIA', max_length=50),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='criticidad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=50),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='estado',
            field=models.CharField(choices=[('en_tiempo', 'En tiempo'), ('atrasada', 'Atrasada'), ('en_riesgo', 'En riesgo'), ('completada', 'Completada')], default='en_tiempo', max_length=50),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='origen',
            field=models.CharField(default='BCN', max_length=100),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='tipo',
            field=models.CharField(default='Ley', max_length=100),
        ),
        migrations.CreateModel(
            name='ComplianceEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('SUGERIDA_IA', 'Sugerida por IA'), ('EN_PROCESO', 'En Proceso'), ('CUMPLIDA', 'Cumplida'), ('NO_APLICA', 'No Aplica')], default='ASIGNADA', max_length=50)),
                ('porcentaje_progreso', models.FloatField(default=0.0)),
                ('origen', models.CharField(choices=[('MOTOR_REGLAS', 'Motor de Reglas'), ('SMART_DISCOVERY_IA', 'Smart Discovery IA')], default='MOTOR_REGLAS', max_length=50)),
                ('justificacion_ia', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_normativas', to='api.empresa')),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_compliances', to='api.normativa')),
            ],
            options={
                'verbose_name': 'Compliance de Empresa',
                'verbose_name_plural': 'Compliances de Empresas',
                'unique_together': {('empresa', 'normativa')},
            },
        ),
    ]
