# Generated by Django 6.1 on 2026-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_empresa_created_at_empresa_es_b2c_ecommerce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado_matching',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Ejecución'), ('EXITOSO', 'Exitoso'), ('ADVERTENCIA', 'Advertencia (0 leyes)'), ('FALLBACK_IA', 'Fallback IA Activado'), ('ERROR', 'Error Crítico')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='log_matching',
            field=models.JSONField(blank=True, default=dict, help_text='Registro detallado del último proceso de matching'),
        ),
    ]
