# Generated by Django 6.1 on 2026-08-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_empresa_estado_matching_empresa_log_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='importa_exporta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instalaciones_industriales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nivel_ingresos',
            field=models.CharField(choices=[('MICRO', 'Microempresa (hasta 2.400 UF)'), ('PEQUENA', 'Pequeña Empresa (2.400 - 25.000 UF)'), ('MEDIANA', 'Mediana Empresa (25.000 - 100.000 UF)'), ('GRANDE', 'Gran Empresa (más de 100.000 UF)')], default='PEQUENA', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='region_operacion',
            field=models.CharField(choices=[('XV', 'Arica y Parinacota'), ('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo'), ('V', 'Valparaíso'), ('RM', 'Metropolitana'), ('VI', 'Libertador Gral. Bernardo O’Higgins'), ('VII', 'Maule'), ('XVI', 'Ñuble'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('XIV', 'Los Ríos'), ('X', 'Los Lagos'), ('XI', 'Aysén del Gral. Carlos Ibáñez del Campo'), ('XII', 'Magallanes y de la Antártica Chilena')], default='RM', max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tiene_sindicato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='trabaja_con_estado',
            field=models.BooleanField(default=False),
        ),
    ]
