# Generated by Django 6.1 on 2026-08-11 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_empresa_importa_exporta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_matriz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='solicitud_arco_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acepto_terminos_y_privacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_aceptacion_consentimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ip_registro',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rut_personal',
            field=models.CharField(blank=True, help_text='Para firma legal / representante', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato +569XXXXXXXX para 2FA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='version_politica_aceptada',
            field=models.CharField(default='v1.0', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroAuditoriaARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_derecho', models.CharField(choices=[('ACCESO', 'Derecho de Acceso'), ('RECTIFICACION', 'Derecho de Rectificación'), ('CANCELACION', 'Derecho de Cancelación (Supresión)'), ('OPOSICION', 'Derecho de Oposición')], max_length=20)),
                ('detalles', models.TextField(help_text='Descripción o justificación de la solicitud ARCO')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_arco', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
