# Generated by Django 6.1 on 2026-08-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_empresa_comuna_empresa_direccion_matriz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceempresa',
            name='estado',
            field=models.CharField(choices=[('PRELIMINAR', 'Preliminar (Pendiente Validación)'), ('VERIFICADA', 'Verificada / Asignada'), ('ASIGNADA', 'Asignada'), ('SUGERIDA_IA', 'Sugerida por IA'), ('EN_PROCESO', 'En Proceso'), ('CUMPLIDA', 'Cumplida'), ('NO_APLICA', 'No Aplica'), ('RECHAZADA', 'Rechazada por Admin')], default='PRELIMINAR', max_length=50),
        ),
    ]
