# Generated by Django 6.1 on 2026-08-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_complianceempresa_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complianceempresa',
            options={},
        ),
        migrations.AlterField(
            model_name='complianceempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='complianceempresa',
            name='normativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.normativa'),
        ),
        migrations.AlterField(
            model_name='complianceempresa',
            name='origen',
            field=models.CharField(default='MOTOR_REGLAS', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado_matching',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='log_matching',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nivel_ingresos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='region_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='criticidad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='estado',
            field=models.CharField(choices=[('en_tiempo', 'En tiempo'), ('atrasada', 'Atrasada'), ('en_riesgo', 'En riesgo'), ('completada', 'Completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='origen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='rubro_aplicable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut_personal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registroauditoriaarco',
            name='detalles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registroauditoriaarco',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroauditoriaarco',
            name='tipo_derecho',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registroauditoriaarco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfilusuario'),
        ),
    ]
