# Generated by Django 6.1 on 2026-08-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_complianceempresa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_modulo', models.CharField(max_length=50)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('criticidad', models.CharField(default='MEDIA', max_length=20)),
                ('estado', models.CharField(default='ABIERTA', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_escalamiento', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
    ]
