# Generated by Django 6.1 on 2026-08-21 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alertacompliance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='responsable_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='hallazgos_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='no_conformidades_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='normativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.normativa'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='tipo',
            field=models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa')], default='interna', max_length=50),
        ),
        migrations.AddField(
            model_name='control',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='api.area'),
        ),
        migrations.AddField(
            model_name='control',
            name='normativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='api.normativa'),
        ),
        migrations.AddField(
            model_name='control',
            name='proxima_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='ultima_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocompliance',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AddField(
            model_name='eventocompliance',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventocompliance',
            name='normativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.normativa'),
        ),
        migrations.AddField(
            model_name='eventocompliance',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=50),
        ),
        migrations.AddField(
            model_name='eventocompliance',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsable'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='normativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.normativa'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='obligacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.obligacion'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsable'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='titulo',
            field=models.CharField(default='Evidencia', max_length=255),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='obligacion',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to='api.area'),
        ),
        migrations.AddField(
            model_name='obligacion',
            name='criticidad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=50),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='normativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.normativa'),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsable'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('ejecutado', 'Ejecutado'), ('pendiente', 'Pendiente'), ('vencido', 'Vencido'), ('proximo', 'Próximo')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='control',
            name='obligacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='api.obligacion'),
        ),
        migrations.AlterField(
            model_name='control',
            name='periodicidad',
            field=models.CharField(default='MENSUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventocompliance',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('cumplido', 'Cumplido'), ('vencido', 'Vencido')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='api.control'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por Vencer'), ('vencido', 'Vencido'), ('pendiente_aprobacion', 'Pendiente Aprobación'), ('desactualizado', 'Desactualizado')], default='vigente', max_length=50),
        ),
        migrations.AlterField(
            model_name='obligacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplido', 'Cumplido'), ('parcial', 'Parcial'), ('en_riesgo', 'En Riesgo')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='planaccion',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('atrasado', 'Atrasado'), ('cerrado', 'Cerrado')], default='abierto', max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricoCumplimientoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('porcentaje_cumplimiento', models.FloatField(default=0.0)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sucursal')),
            ],
            options={
                'unique_together': {('empresa', 'sucursal', 'area', 'mes', 'anio')},
            },
        ),
    ]
