# Generated by Django 6.1 on 2026-08-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_area_responsable_principal_auditoria_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoriaarco',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
    ]
