# Generated by Django 6.1 on 2026-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_registroauditoriaarco_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='severidad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=50),
        ),
        migrations.AddField(
            model_name='objetivochecklist',
            name='criticidad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=50),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='estrategia',
            field=models.CharField(choices=[('Mitigar', 'Mitigar'), ('Transferir', 'Transferir'), ('Aceptar', 'Aceptar'), ('Eliminar', 'Eliminar')], default='Mitigar', max_length=50),
        ),
    ]
