# Generated by Django 6.1 on 2026-08-26 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_incidente_severidad_objetivochecklist_criticidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareapendiente',
            name='compliance_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='api.complianceempresa'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='api.control'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='normativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='api.normativa'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='obligacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='api.obligacion'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('critica', 'Crítica')], default='media', max_length=50),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareapendiente',
            name='asociada_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tareapendiente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_pendientes', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='tareapendiente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='tareapendiente',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
