# Generated by Django 6.1 on 2026-08-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tareapendiente_compliance_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
