# Generated by Django 6.1 on 2026-08-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_responsable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceempresa',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
