# Generated by Django 6.1 on 2026-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_complianceempresa_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareapendiente',
            name='archivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_tareas/'),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='comentario_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='comentario_progreso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareapendiente',
            name='nombre_archivo_evidencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
