# Generated by Django 6.1 on 2026-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tareapendiente_archivo_evidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normativa',
            name='criterio_aplicabilidad',
            field=models.CharField(choices=[('UNIVERSAL', 'Universal (Todas las empresas con personal)'), ('DOTACION', 'Por Dotación de Empleados (min_empleados)'), ('TRIGGER', 'Por Actividad / Trigger Específico'), ('SECTORIAL', 'Sectorial / Rubro Específico')], default='UNIVERSAL', max_length=50),
        ),
        migrations.AddField(
            model_name='normativa',
            name='materia',
            field=models.CharField(choices=[('LABORAL', '💼 Laboral & Seguridad'), ('PRIVACIDAD', '🔒 Datos Personales & Ciberseguridad'), ('PENAL_COMPLIANCE', '⚖️ Delitos Económicos & MPD'), ('CONSUMO', '🛒 Consumidor & E-commerce'), ('AMBIENTAL', '♻️ Medioambiente & REP'), ('FINANCIERO', '💳 Financiero & Fintec'), ('CORPORATIVO', '🏢 Corporativo & Sociedades')], default='CORPORATIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='normativa',
            name='numero_oficial',
            field=models.CharField(blank=True, help_text='Número canónico de ley, ej: 21643 o DS-594', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='normativa',
            name='trigger_asociado',
            field=models.CharField(blank=True, help_text='Campo booleano de Empresa que la activa, ej: maneja_datos_personales, es_b2c_ecommerce', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='es_b2c_ecommerce',
            field=models.BooleanField(default=False, help_text='Gatilla [Ley del Consumidor (SERNAC)] y comercio electrónico.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='genera_residuos_rep',
            field=models.BooleanField(default=False, help_text='Gatilla [Ley REP].'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='importa_exporta',
            field=models.BooleanField(default=False, help_text='Gatilla normativas Aduaneras.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='instalaciones_industriales',
            field=models.BooleanField(default=False, help_text='Gatilla [Ley Ambiental DIA/EIA] y [DS 594].'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='maneja_datos_personales',
            field=models.BooleanField(default=False, help_text='Gatilla [Ley de Protección de la Vida Privada] y [Ley 21.719].'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='procesa_pagos',
            field=models.BooleanField(default=False, help_text='Gatilla normativas de la CMF y prevención de lavado de activos.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tiene_sindicato',
            field=models.BooleanField(default=False, help_text='Gatilla normativa de negociación colectiva.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tiene_trabajadores',
            field=models.BooleanField(default=True, help_text='Gatilla [Código del Trabajo], [Ley Karin], [Ley Sanna].'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='trabaja_con_estado',
            field=models.BooleanField(default=False, help_text='Gatilla [Ley de Compras Públicas].'),
        ),
    ]
