# Generated by Django 6.1 on 2026-08-29 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_normativa_criterio_aplicabilidad_normativa_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeyOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bcn', models.CharField(blank=True, help_text='ID oficial en BCN / Ley Chile', max_length=100, null=True, unique=True)),
                ('numero_oficial', models.CharField(blank=True, help_text='Ej: Ley 19.628, DS 594', max_length=50, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('organismo_emisor', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('resumen_general', models.TextField(blank=True, null=True)),
                ('fecha_promulgacion', models.DateField(blank=True, null=True)),
                ('fecha_ultima_modificacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ley Oficial (Catálogo Maestro)',
                'verbose_name_plural': 'Leyes Oficiales (Catálogo Maestro)',
            },
        ),
        migrations.CreateModel(
            name='ArticuloLey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_articulo', models.CharField(help_text='Ej: Art. 4, Art. 211-A', max_length=50)),
                ('texto_original', models.TextField(help_text='Texto legal oficial completo extraído de la BCN')),
                ('texto_resumido', models.TextField(help_text='Extracto operativo / clave destilada para IA RAG')),
                ('categoria_tematica', models.CharField(blank=True, max_length=100, null=True)),
                ('sanciones_asociadas', models.TextField(blank=True, null=True)),
                ('indexado_en_rag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='api.leyoficial')),
            ],
            options={
                'verbose_name': 'Artículo de Ley',
                'verbose_name_plural': 'Artículos de Ley',
                'unique_together': {('ley', 'numero_articulo')},
            },
        ),
    ]
