# Generated by Django 6.1 on 2026-09-01 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0021_leyoficial_articuloley'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteKarin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('es_anonimo', models.BooleanField(default=True)),
                ('denunciante_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('denunciante_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descripcion_hechos', models.TextField()),
                ('estado', models.CharField(choices=[('INGRESADA', 'Denuncia Ingresada'), ('CAUTELARES_APLICADAS', 'Medidas Cautelares Aplicadas'), ('INVESTIGACION', 'Investigación Interna'), ('RESUELTA', 'Resolución / Reporte DT')], default='INGRESADA', max_length=30)),
                ('medidas_cautelares_adoptadas', models.TextField(blank=True, help_text='Requisito legal para pasar a fase de Investigación', null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_karin', to='api.empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_karin_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente Ley Karin',
                'verbose_name_plural': 'Incidentes Ley Karin',
            },
        ),
        migrations.CreateModel(
            name='RiesgoPenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Cohecho, Lavado de Activos', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_inherente', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos_penales', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Riesgo Penal (Ley 21.595)',
                'verbose_name_plural': 'Riesgos Penales',
            },
        ),
        migrations.CreateModel(
            name='ControlRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Cláusula anticorrupción en contratos', max_length=255)),
                ('fecha_proxima_revision', models.DateField()),
                ('estado_evidencia', models.CharField(choices=[('AL_DIA', 'Al Día'), ('VENCIDO', 'Vencido'), ('PENDIENTE_REVISION', 'Pendiente de Revisión')], default='AL_DIA', max_length=30)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='gestion_operativa.riesgopenal')),
            ],
            options={
                'verbose_name': 'Control Preventivo',
                'verbose_name_plural': 'Controles Preventivos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('tipo_arco', models.CharField(choices=[('ACCESO', 'Acceso'), ('RECTIFICACION', 'Rectificación'), ('CANCELACION', 'Cancelación'), ('OPOSICION', 'Oposición')], max_length=20)),
                ('solicitante_nombre', models.CharField(max_length=255)),
                ('solicitante_email', models.EmailField(max_length=254)),
                ('usuario_tipo', models.CharField(default='B2C', max_length=50)),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('REVISANDO', 'Revisando'), ('RESOLVIENDO', 'Resolviendo'), ('RESUELTA', 'Resuelta'), ('RECHAZADA', 'Rechazada')], default='RECIBIDA', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento_sla', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_arco', to='api.empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_arco_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
            },
        ),
    ]
