# Generated by Django 6.1 on 2026-08-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0020_normativa_criterio_aplicabilidad_normativa_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaIaEmpresa',
            fields=[
            ],
            options={
                'verbose_name': '🤖 Auditoría RAG / Asignación',
                'verbose_name_plural': '🤖 1. Consola de Auditoría RAG',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.empresa',),
        ),
        migrations.CreateModel(
            name='RegistroAuditoriaRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_ia', models.CharField(default='llama3.2:3b', max_length=50)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('resumen_ejecutivo', models.TextField(blank=True, null=True)),
                ('normativas_detectadas', models.IntegerField(default=0)),
                ('tareas_generadas', models.IntegerField(default=0)),
                ('exito', models.BooleanField(default=True)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('datos_completos_json', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rag', to='api.empresa')),
            ],
            options={
                'verbose_name': '📜 Log de Auditoría IA',
                'verbose_name_plural': '📜 2. Historial de Ejecuciones RAG',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
