# Generated by Django 6.1 on 2026-08-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoriarag',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado y Aplicado'), ('RECHAZADO', 'Rechazado / Descartado')], default='PENDIENTE', max_length=20),
        ),
    ]
